### ISSUE TITLE
Ignore commented lines when checking for broken calls

### ISSUE THREAD

**Issue by eversteeg** [Dexels/dexels.repository#1]
In a tipi window I encountered some commented code with callservice tags in it.
The dependency analyzer still saw it as a broken link.

**Comment by cbrouwer** [comment]
Is this a real issue? How much commented-out code do we have? Why do we have this commented out? We use git for a reason; in general there shouldn't really be any commented out code.

Implementation wise this would mean changing the simply and fast code grep, to a xml interpreter that removes commented out code. For now that seems overkill for this.
