### ISSUE TITLE
Navajo dependency broken links false positives

### ISSUE THREAD

**Issue by StefanICT** [Dexels/dexels.repository#4]
Happens in articles with the element command (article/clubgegevens).

![screen shot 2016-04-22 at 16 16 12](https://cloud.githubusercontent.com/assets/3540810/14744060/478a2c6c-08a5-11e6-91c6-8e7e6dfa2218.png)

**Comment by cbrouwer** [comment]
Are you using an up-to-date version of the depedency analyzer?

**Comment by cbrouwer** [comment]
Moved to proper repo. See https://github.com/Dexels/navajo.tools/issues/7
